#!/usr/bin/env php
<?php

namespace BrainGames\Engine;

require_once __DIR__ . '/../../vendor/autoload.php';

use function cli\line;
use function cli\prompt;
use function BrainGames\Engine\greeting;
use function BrainGames\Engine\questions;
use function BrainGames\Engine\comparison;

$nameGame = 'BrainEven';

$name = greeting();

line('Answer "yes" if the number is even, otherwise answer "no".');
$i = 0;
while ($i < 3) { 
$isEven = questions($nameGame);
$answerUser = prompt('Your answer');
$i = comparison($isEven, $answerUser, $i, $name);
if ($i == 3) {
print_r("Congratulations, {$name}!\n");
}
}
